// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "user": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/JormungandrK/microservice-user/design
// --out=$(GOPATH)/src/github.com/JormungandrK/microservice-user
// --version=v1.3.0

package app
