// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "user": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/Microkubes/microservice-user/design
// --out=$(GOPATH)/src/github.com/Microkubes/microservice-user
// --version=v1.3.1

package app
